# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  application:
    name: 4Test
  datasource:
    url: jdbc:mysql://localhost:3306/pro4test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456xm
    driver-class-name: com.mysql.cj.jdbc.Driver
